apiVersion: v1
kind: Service
metadata:
  # Unique key of the service instance
  name: angular-webapp
spec:
  selector:
    # It defines which pods are going to be selected or considered
    # by this service
    # Select all the pods with value "webapp" for the labe "mylabelname"
    mylabelname: webapp
  ports:
    - name: http
      port: 80 # This service is going to talk to port 80 of pods
      nodePort: 30080 #node port has a constraint to be >30000
      
    # type: LoadBalancer for load balancer
    # type: ClusterIP # if the service is only internally accessible
  type: NodePort # this means we are going to expose the port through the node, to the external world